# Generated by Django 2.1.4 on 2019-02-16 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anteproyecto', '0002_auto_20190215_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnteProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fila', models.IntegerField()),
                ('total', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('concepto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('partidaGenerica', models.IntegerField()),
                ('capitulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.Capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enero', models.FloatField(max_length=30)),
                ('febrero', models.FloatField(max_length=30)),
                ('marzo', models.FloatField(max_length=30)),
                ('abril', models.FloatField(max_length=30)),
                ('mayo', models.FloatField(max_length=30)),
                ('junio', models.FloatField(max_length=30)),
                ('julio', models.FloatField(max_length=30)),
                ('agosto', models.FloatField(max_length=30)),
                ('septiembre', models.FloatField(max_length=30)),
                ('octubre', models.FloatField(max_length=30)),
                ('noviembre', models.FloatField(max_length=30)),
                ('diciembre', models.FloatField(max_length=30)),
                ('capitulo', models.IntegerField()),
                ('anteProyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.AnteProyecto')),
            ],
        ),
        migrations.CreateModel(
            name='PartidaEspecifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PartidaGenerica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('partidaEspecifica', models.IntegerField()),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anteproyecto.Concepto')),
            ],
        ),
        migrations.AddField(
            model_name='partidaespecifica',
            name='partidaGenerica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anteproyecto.PartidaGenerica'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='fila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.Fila'),
        ),
    ]
