# Generated by Django 2.1.4 on 2019-02-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0005_auto_20190215_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartidaGenerica',
        ),
    ]
