# Generated by Django 2.1.4 on 2019-02-22 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_profile'),
        ('anteproyecto', '0012_auto_20190216_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteproyecto',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.Profile'),
        ),
    ]
