# Generated by Django 2.1.4 on 2019-03-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0019_auto_20190306_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='estadoN',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='estadoN',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='anteproyecto',
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='estado',
            field=models.ManyToManyField(to='anteproyecto.Estado'),
        ),
    ]
