# Generated by Django 2.1.4 on 2019-04-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0020_auto_20190306_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
