# Generated by Django 2.2 on 2019-04-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0024_auto_20190423_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antepi',
            name='imagen',
            field=models.ImageField(upload_to='apimg/'),
        ),
    ]
