# Generated by Django 2.2 on 2019-04-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0025_auto_20190423_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antepi',
            name='imagen',
            field=models.ImageField(upload_to='apimg/%Y/%m/%d/'),
        ),
    ]
