# Generated by Django 2.2 on 2019-04-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0028_auto_20190424_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteproyecto',
            name='estado',
            field=models.CharField(choices=[('EJ', 'Ejercido'), ('NE', 'Noejercido'), ('ED', 'Endesarrollo'), ('CP', 'Completo')], default='ED', max_length=2),
        ),
    ]
