# Generated by Django 2.2 on 2019-05-01 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0035_auto_20190427_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='capitulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.Capitulo'),
        ),
        migrations.AlterField(
            model_name='fila',
            name='anteProyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.AnteProyecto'),
        ),
        migrations.AlterField(
            model_name='fila',
            name='capitulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.Capitulo'),
        ),
        migrations.AlterField(
            model_name='fila',
            name='concepto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.Concepto'),
        ),
        migrations.AlterField(
            model_name='fila',
            name='partidaespecifica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.PartidaEspecifica'),
        ),
        migrations.AlterField(
            model_name='fila',
            name='partidagenerica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.PartidaGenerica'),
        ),
        migrations.AlterField(
            model_name='partidaespecifica',
            name='partidaGenerica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anteproyecto.PartidaGenerica'),
        ),
        migrations.AlterField(
            model_name='partidagenerica',
            name='concepto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anteproyecto.Concepto'),
        ),
    ]
