# Generated by Django 2.2 on 2019-05-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0036_auto_20190430_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='estado',
            field=models.CharField(blank=True, choices=[('Ejercido', 'Ejercido'), ('No_Ejercido', 'No Ejercido'), ('Desarrollo', 'Desarrollo')], default='Desarrollo', max_length=15),
        ),
    ]
