# Generated by Django 2.2 on 2019-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0037_auto_20190502_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='fila',
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='filas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
