# Generated by Django 2.2 on 2019-05-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0038_auto_20190503_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidaespecifica',
            old_name='partidaGenerica',
            new_name='partidagenerica',
        ),
    ]
