# Generated by Django 2.1.4 on 2019-02-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
