# Generated by Django 2.1.4 on 2019-01-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
