# Generated by Django 2.1.4 on 2019-02-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0003_auto_20190215_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='fila',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='capitulo',
        ),
        migrations.RemoveField(
            model_name='fila',
            name='anteProyecto',
        ),
        migrations.RemoveField(
            model_name='partidagenerica',
            name='concepto',
        ),
        migrations.DeleteModel(
            name='Capitulo',
        ),
        migrations.DeleteModel(
            name='Concepto',
        ),
        migrations.DeleteModel(
            name='Fila',
        ),
    ]
