# Generated by Django 2.1.4 on 2019-02-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0004_auto_20190215_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnteProyecto',
        ),
        migrations.RemoveField(
            model_name='partidaespecifica',
            name='partidaGenerica',
        ),
        migrations.DeleteModel(
            name='PartidaEspecifica',
        ),
    ]
