# Generated by Django 2.1.4 on 2019-02-16 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0009_auto_20190216_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='concepto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fila',
            name='partidaespecifica',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fila',
            name='partidagenerica',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partidaespecifica',
            name='fila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.Fila'),
        ),
        migrations.AddField(
            model_name='partidagenerica',
            name='fila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.Fila'),
        ),
    ]
