# Generated by Django 2.1.4 on 2019-02-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0013_anteproyecto_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='profile',
        ),
    ]
