# Generated by Django 2.1.4 on 2019-03-06 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0017_auto_20190223_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoN', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='anteproyecto',
            old_name='total',
            new_name='totalA',
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='estadoN',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fila',
            name='totalF',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fila',
            name='abril',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fila',
            name='agosto',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fila',
            name='diciembre',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fila',
            name='enero',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fila',
            name='febrero',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fila',
            name='julio',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fila',
            name='junio',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fila',
            name='marzo',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fila',
            name='mayo',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fila',
            name='noviembre',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fila',
            name='octubre',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='fila',
            name='septiembre',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='estado',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anteproyecto.AnteProyecto'),
        ),
    ]
