# Generated by Django 2.2 on 2019-04-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0026_auto_20190423_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteproyecto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='apimg/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='AntePI',
        ),
    ]
