# Generated by Django 2.2 on 2019-04-25 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0027_auto_20190423_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='apimg/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
