# Generated by Django 2.2 on 2019-04-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0029_anteproyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='estado',
            field=models.CharField(choices=[('EJ', 'Ejercido'), ('NE', 'No ejercido'), ('ED', 'En desarrollo'), ('CP', 'Completo')], default='ED', max_length=2),
        ),
    ]
