# Generated by Django 2.2 on 2019-04-26 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0030_auto_20190425_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='estado',
        ),
    ]
