# Generated by Django 2.2 on 2019-04-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0031_remove_anteproyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteproyecto',
            name='estado',
            field=models.CharField(choices=[('Desarrollo', 'En desarrollo'), ('Completo', 'Completo'), ('Ejercido', 'Ejercido'), ('NO_EJERCIDO', 'No Ejercido')], default='Desarrollo', max_length=15),
        ),
    ]
