# Generated by Django 2.2 on 2019-04-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0032_anteproyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='estado',
            field=models.CharField(choices=[('Ejercido', 'Ejercido'), ('NO_EJERCIDO', 'No Ejercido')], default='NO_EJERCIDO', max_length=15),
        ),
    ]
