# Generated by Django 2.2 on 2019-04-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0033_auto_20190425_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='estado',
            field=models.CharField(choices=[('Ejercido', 'Ejercido'), ('No_Ejercido', 'No Ejercido'), ('Desarrollo', 'Desarrollo')], default='Desarrollo', max_length=15),
        ),
    ]
