# Generated by Django 2.2 on 2019-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anteproyecto', '0034_auto_20190425_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='totalA',
            field=models.FloatField(blank=True, default=0, max_length=30, null=True),
        ),
    ]
